server:
  port: 8080

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: false
          routes:
            - id: usuarios-route
              uri: lb://usuarios
              predicates:
                - Path=/api/usuarios/**
            # --- NUEVA RUTA PARA PROYECTOS ---
            - id: proyectos-route
              uri: lb://proyectos
              predicates:
                - Path=/api/proyectos/**
            # --- NUEVA RUTA PARA EQUIPOS ---
            - id: equipos-route
              uri: lb://equipos
              predicates:
                - Path=/api/equipos/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1