server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-server


management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://${eureka.instance.hostname}:${server.port}/eureka/}