server:
  port: 8086

spring:
  application:
    name: proyectos
  threads:
    virtual:
      enabled: true # Habilitamos Virtual Threads de Java 21
  
  datasource:
    url: jdbc:mysql://localhost:3306/db_innovatech_proyectos?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1